id: P174387EA
initial_creation_type: ocr
source_metadata:
  volumes:
    ca3ed7acba424240aab552b310b7f022:
      base_file: v073.txt
      image_group_id: I1PD95918
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་ཉན་ཐོས་ཀྱི་ས།
      total_pages: 1125
      volume_number: 73
vol2fn:
  v073: v073.txt
